### ISSUE TITLE
Can't get past Title Screen

### ISSUE THREAD

**Issue by okezue** [jessica-huynh/Knot#1]

**Comment by jessica-huynh** [comment]
What error message are you getting exactly? Also, if the issue is with the API keys, you can always just hard code them into the app by following these instructions:

1. Go to `Knot/API/PlaidAPI.swift`
2. In the class' `init`, remove line 33 (i.e. `let keys = KnotKeys()`). You may also want to remove the import statement if you're having trouble installing the dependency. So remove `import Keys` on line 11.
3. Replace lines 34, 35 and 37 with your pubic key, client ID and secret key respectively.

**Comment by BellAI-Code** [comment]
Thanks! I will try that now and see if it works!

**Comment by jessica-huynh** [comment]
No problem, keep me posted!

PS Make sure you're using the right keys (sandbox vs development environment) and change the environment as appropriate. :)

**Comment by BellAI-Code** [comment]
I do I get the publickey, clientid and secret key if im using Plaid sandbox?

**Comment by BellAI-Code** [comment]
Is it the same as username and password, and then secret key empty?

**Comment by jessica-huynh** [comment]
No, you will need all 3 keys for the app to work no matter what environment. Go to `https://dashboard.plaid.com/team/keys`. The clientID and public key will be at the top. And then scroll down and you should see the secret key for the sandbox environment. When you apply for a development key, it will be different from the sandbox one.

**Comment by BellAI-Code** [comment]
For some reason, I only see my clientID and the secure text secret key. Do you know where I can find the public Key. Thanks so much for your help!

**Comment by BellAI-Code** [comment]
Plaid only offers link tokens now, instead of public keys. Can it still be substituted?

**Comment by BellAI-Code** [comment]
But I don't even know where to find the link token lol

**Comment by jessica-huynh** [comment]
Ah no wonder. No this isn't something that can be substituted. I'd have to add a new API endpoint to generate the link token. I can update the app this weekend. You can always have a go at it if your impatient as well!

Anyway, thanks for bringing this to my attention. I had no idea Plaid made these changes! Looks like it took effect a weeks ago.

**Comment by BellAI-Code** [comment]
020-08-13 19:45:24.719689-0400 Knot[5398:212021] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2020-08-13 19:45:24.720321-0400 Knot[5398:212021] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2020-08-13 19:45:24.720840-0400 Knot[5398:212021] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2020-08-13 19:45:24.721646-0400 Knot[5398:212021] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2020-08-13 19:45:24.721984-0400 Knot[5398:212021] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2020-08-13 19:45:24.722432-0400 Knot[5398:212021] [framework] CUICatalog: Invalid asset name supplied: '(null)'
2020-08-13 19:45:24.722841-0400 Knot[5398:212021] [framework] CUICatalog: Invalid asset name supplied: '(null)'
Failed to link account due to: public_key must be a properly formatted, non-empty string
metadata: ["status": <null>, "link_session_id": <null>, "request_id": <null>]
(lldb)

**Comment by okezue** [comment]
These are errors, along with the in-app error saying "Whoops something went wrong"

**Comment by jessica-huynh** [comment]
Yup, it has to do with the new link token. See my reply above. Will get to it later on this week.

**Comment by okezue** [comment]
Yeah, I'll try to update it too, but I'll be looking forward to your updates as well. You said you'll be doing it over the weekend right? Also sorry for the message it didn't update with your comment. When do you think it will be live? So happy talking to you!

**Comment by jessica-huynh** [comment]
Should have the changes done by the end of the weekend. I will update you in this thread when I'm done. 👍

**Comment by okezue** [comment]
Ok, thanks!

**Comment by jessica-huynh** [comment]
Just pushed the updates. Let me know if it works for you now.

**Comment by okezue** [comment]
Will do! Great to hear!

**Comment by okezue** [comment]
Get this error: libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by okezue** [comment]
And for some reason, the pod doesn't ask for the keys...

**Comment by okezue** [comment]
Yep it worked!

**Comment by okezue** [comment]
tysm! I also tried using the same method haha!
