### ISSUE TITLE
Switch Doesn't Work

### ISSUE THREAD

**Issue by okezue** [jessica-huynh/Knot#2]
Hello again!

When I switch from Sandbox to Development mode, it takes forever to load, but there are no errors. Any ideas on why this is happening?

**Comment by okezue** [comment]
The only thing is that development mode takes so long to load, is this not an error?

**Comment by jessica-huynh** [comment]
Yes I noticed that as well. It comes from Plaid's side unfortunately (specifically from the `/accounts/balance/get` endpoint whenever the app fetches the updated account balance). You don't see this problem in `sandbox` because they don't actually have to fetch real account data. Knot does have background refreshing though so the call to that particular endpoint doesn't necessarily happen every time the user opens the app from the background. Other than that, it's out of my control- sorry! I feel like they must speed up their `production` environment though so if you're willing to upgrade to that, you can give it a shot.

**Comment by okezue** [comment]
Oh ok! But development still works right? Just takes a while?

**Comment by jessica-huynh** [comment]
Yup it 100% does. The fetch just takes long! Like 10+ seconds at times... again it sucks but out of my control.

**Comment by okezue** [comment]
good to hear! Mine is taking like 3+ minutes lol

**Comment by okezue** [comment]
But I think its just the connection

**Comment by okezue** [comment]
Yeah, production seems like the way to go! Thanks!
